### ISSUE TITLE
Website issues

### ISSUE THREAD

**Issue by fuzzthink** [mint-lang/mint-website-rails#11]
Example compile errors:
https://www.mint-lang.com/examples/drag
https://www.mint-lang.com/examples/counter
https://www.mint-lang.com/try (same eg. code as counter seems like)

https://guide.mint-lang.com/ can't be reached. git-book issue per https://github.com/mint-lang/mint/issues/125 ?

**Comment by Sija** [comment]
> Example compile errors:
> https://www.mint-lang.com/examples/drag
> https://www.mint-lang.com/examples/counter
> https://www.mint-lang.com/try (same eg. code as counter seems like)

All of those lead to `404` fyi.

**Comment by gdotdesign** [comment]
@fuzzthink I think you are seeing the old website because of service workers, if you delete (unregister) it you should be able to see the new one.

**Comment by fuzzthink** [comment]
Ok, unregistered service workers for the site via https://www.codementor.io/@himank/how-to-unregister-service-workers-n8mzf5jce

Hmm, was it because I (or anyone who) visited the old site will always see the old site?

**Comment by gdotdesign** [comment]
Yes it was because you visited the old site and it got cached, anyone else who visited probably has the same issue.

**Comment by GavinRay97** [comment]
@gdotdesign @fuzzthink Ahh thank you. I have been following Mint for a while and was super confused when the Reddit and Hacker News threads got popular but a lot of the site-content was broken and didn't match up to the comments people were making about the pages.

Page was cached.
