### ISSUE TITLE
Register mint-lang.org, allow non-www subdomain

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint-website-rails#39]
This is a request to allow `https://mint-lang.com` to work, I've typed this a few times to friends and the link doesn't work. Only `https://www.mint-lang.com` works.

This is also a request to register `mint-lang.org`, for the same reason, I've already typed it a few times to friends and didn't realize it was broken. This one isn't as critical as the first. `mint.dev` might be nice, too.

**Comment by s0kil** [comment]
We could redirect
`http://www.mint-lang.com`,
`http://mint-lang.com`,
`https://www.mint-lang.com`
to `https://mint-lang.com`.

**Comment by lukepighetti** [comment]
That sounds like a great solution.

**Comment by gdotdesign** [comment]
Done :)

**Comment by lukepighetti** [comment]
Now getting a not-private error. Is there a settling time?

<img width="704" alt="Screen Shot 2020-05-03 at 7 30 04 AM" src="https://user-images.githubusercontent.com/666539/80913094-ed17b080-8d0f-11ea-89a0-5086c792eb47.png">

**Comment by gdotdesign** [comment]
I don't know probably it's some SSL issue: the site is on Heroku, the domain on GoDaddy so there might be a conflict there. I'll try to investigate some time next week.

**Comment by s0kil** [comment]
@lukepighetti Could you try again? It seems to operate without issues.

**Comment by lukepighetti** [comment]
Still problematic. Both times I tried were on Safari.

**Comment by gdotdesign** [comment]
I've looked into this: We are using forwarding thingy from GoDadday which does not seem to work with HTTPS -> HTTPS forwards https://uk.godaddy.com/community/Managing-Domains/Forwarding-from-HTTPS/td-p/55176

So I will need to set this up some other way, maybe through AWS or something.

**Comment by s0kil** [comment]
@gdotdesign Also want to mention Cloudflare, they offer very powerful and simple tools to do such things.

**Comment by gdotdesign** [comment]
@s0kil thanks, Cloudflare works :tada: 

I moved mint-lang.org there so it's working now as expected, I'll move mint-lang.com as well in the next few days.

**Comment by s0kil** [comment]
@gdotdesign Great, as a benefit, the website loads faster.

**Comment by s0kil** [comment]
Please reopen if you continue to encounter issues.
