### ISSUE TITLE
Explicitly state that mint-lang has tree shaking as a feature

### ISSUE THREAD

**Issue by lukepighetti** [mint-lang/mint-website-rails#45]
I think tree shaking in Mint is a compelling feature that should be explicitly stated on the website. Perhaps in the `Batteries Included` section on the front page?

Thoughts?

Should we call it `tree shaking` or `dead code elimination`?

**Comment by lukepighetti** [comment]
Potentially resolved by https://github.com/mint-lang/mint-website-rails/pull/46

**Comment by s0kil** [comment]
@lukepighetti Could this instead be in the README? We should not try to list every single feature on the homepage, only the major features.

**Comment by lukepighetti** [comment]
That's a great point, I'm going to close this issue and my pull request. Thanks!
