### ISSUE TITLE
What does it mean to `navigate in a smart way`?

### ISSUE THREAD

**Issue by s0kil** [mint-lang/mint-website-rails#6]
https://github.com/mint-lang/mint-website-rails/blob/f219c8a7b4187b2d837f9df1472a4c07f758359e/app/views/landings/index.haml#L227-L228

**Comment by gdotdesign** [comment]
Actually the reference does not contain a description for this, but a blog post does :D
https://www.mint-lang.com/blog/routing the `Navigating to a new URL` section.

Maybe I should copy that part over to the reference.

**Comment by s0kil** [comment]
I'm not sure what the best action is in this case, just suggesting to make the introduction clear, since it's on the landing page.

**Comment by gdotdesign** [comment]
This is what I could come up with :sweat_smile:  

` The runtime handles clicks on anchor tags and navigates without reloading the page.`
