### ISSUE TITLE
Is the sandbox disabled?

### ISSUE THREAD

**Issue by nilslindemann** [mint-lang/mint-website-rails#79]
Because nothing works there. I can not even delete my sandboxes. I click on the delete button, the sandbox goes away, I go back to 'my sandboxes', it is still there. I can just create sandboxes, pretty white, empty sandboxes. I now have six empty sandboxes. Wait, no, *clickclickclick...clickclickclick ... clickclickclick*, 31.

**Comment by gdotdesign** [comment]
Sorry about this, when updating to 0.12.0 the executable was not executable :facepalm: It should work now.

**Comment by nilslindemann** [comment]
Hmm, this works slightly better now – just one sandbox left :-) – but still, can not do much. The format button works perfect in Iridium, but in Firefox and Chromium there is a ~ 20 seconds delay. The compile button is dysfunctional in all three browsers.

**Comment by gdotdesign** [comment]
I've updated the compiler backend from Rails+binary to just the binary itself in an other host, this should speed up both compilation and formatting. For me it's now under 1s.

**Comment by nilslindemann** [comment]
On Windows 7, despite the browsers mentioned, I have now tested the site with

* a fresh Google Chrome Portable, version 90.0.4430.72 [Download URL](https://netcologne.dl.sourceforge.net/project/portableapps/Google%20Chrome%20Portable/GoogleChromePortable_90.0.4430.72_Rebuild_online.paf.exe)
* a fresh Firefox Portable, version 88. [Download URL](https://nav.dl.sourceforge.net/project/portableapps/Mozilla%20Firefox%2C%20Portable%20Ed./Mozilla%20Firefox%2C%20Portable%20Edition%2088.0/FirefoxPortable_88.0_German.paf.exe)
* a fresh Opera Portable, version 75.0.3969.171. [Download URL](https://download3.portableapps.com/portableapps/OperaPortable/OperaPortable_75.0.3969.171.paf.exe?20190321)

I also tested on a fresh installed Linux Mint 20.1-cinnamon-64bit, on another Laptop, fresh Firefox version 88.

I can delete and create sandboxes, and formatting also happens quite fast (one or two seconds). But the compile button produces nothing in any of these browsers. Just a white window on the right. The code I tested was the top right code example on the [start page](https://www.mint-lang.com/). 

If it helps, I can upload screen videos to my YouTube account. But they will just show what i described.

Maybe this is related: When I tested the downloaded mint binary a while ago on a Fedora 33 Linux XFCE, I also had loong compilation times, like, minutes.

That is all I can say about it. The site does not work for me.

**Comment by gdotdesign** [comment]
Thank you for all the testing :pray: it helps me improve the sandbox!

>  The code I tested was the top right code example on the [start page](https://www.mint-lang.com/).

That code compiles but you see a white page because there is no `Main` component, if you change `component Counter` to `component Main` it should work.

This makes me wonder if there should be an error for the case of missing `Main`.

**Comment by nilslindemann** [comment]
Oh, ok, the first example from the docs actually produces something

**Comment by nilslindemann** [comment]
Yes, cool, that fixed. Yeah sure, add more of those pretty looking error messages. Ah, I wish my python would print such nice error messages ...

**Comment by nilslindemann** [comment]
Wonderful, thanks a ton for your support.

**Comment by gdotdesign** [comment]
> Wonderful, thanks a ton for your support.

Your welcome :pray: :+1:
