### ISSUE TITLE
Freezing the Sandbox

### ISSUE THREAD

**Issue by nilslindemann** [mint-lang/mint-website-rails#83]
I was playing around with an example from the [docs ](https://www.mint-lang.com/guide/reference/components/lifecycle-functions) (which btw does not compile, guess the return type has changed) and managed to freeze the Sandbox:

https://sandbox.mint-lang.com/sandboxes/WfDzWiFfBK1WXw

Here is a screenshot of the code (can not copy it):

https://i.imgur.com/yAsB9Cb.jpg

If iam not wrong I accidently infinitely triggered `componentDidUpdate`. I guess that should not be triggered when no changes were made, should it?

**Comment by gdotdesign** [comment]
> If iam not wrong I accidently infinitely triggered `componentDidUpdate`. I guess that should not be triggered when no changes were made, should it?

You are correct, it froze because of the update in `componenDidUpdate`. At first the behavior was like it is now, then it changed so that only actual updates triggered it but it had side effects and we decided to change it back again, you can read more about it in this issue https://github.com/mint-lang/mint/issues/316

**Comment by nilslindemann** [comment]
Ok. This leads to a theoretical and a practical question.

Theoretical: How would i write this code so that i dont trap into this?

Practical: How do i delete that sandbox :-)

**Comment by nilslindemann** [comment]
Ok. I was able to resolve the first question myself, i need to [first check if the state has changed, and only if it did, update it](https://sandbox.mint-lang.com/sandboxes/cx-Oe6fDUBOApA).

In a vanilla Javascript MVC implementation, where updating the model triggers notifying the observer views, the behaviour is the same when these views incorrectly update the model again after having been notified. Also results in an infinite recursion. The only difference is that the code is three times as long :-)

I am closing this, asking if you could delete [this](https://sandbox.mint-lang.com/sandboxes/WfDzWiFfBK1WXw) and [this](https://sandbox.mint-lang.com/sandboxes/vreeycMNk-Eyow) Sandbox if you have the time. They freeze the tab. Sorry for the inconveniences.

**Comment by gdotdesign** [comment]
> I am closing this, asking if you could delete [this](https://sandbox.mint-lang.com/sandboxes/WfDzWiFfBK1WXw) and [this](https://sandbox.mint-lang.com/sandboxes/vreeycMNk-Eyow) Sandbox if you have the time. They freeze the tab. Sorry for the inconveniences.

I've deleted them.
