### ISSUE TITLE
Mistake in the example code

### ISSUE THREAD

**Issue by mSiotniHS** [mint-lang/mint-website-rails#98]
I think there is a mistake in the example code here: https://www.mint-lang.com/api/modules/Array#reverse
```
Array.reverse([1, 2, 3]) == [4, 3, 2, 1]
```

I'm afraid it should be either without "4" on the right side or with "4" on the left side.

**Comment by mSiotniHS** [comment]
Closing it because the source of documentation is actually on the main repository.

**Comment by Sija** [comment]
Fixed in https://github.com/mint-lang/mint/commit/570fa0b2d787c47494243f65e59f5e93641ede26
